- name: Create group
  group:
    name: "{{ retropie_group }}"
  tags:
    - retropie

- name: Create user
  user:
    name: "{{ retropie_user }}"
    group: "{{ retropie_group }}"
    append: yes
    groups: "{{ retropie_extra_groups }}"
  register: user_info
  tags:
    - retropie

- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes
    cache_valid_time: 90
  tags:
    - retropie

- name: Clone repo
  git:
    repo: "{{ retropie_git_repo }}"
    dest: "{{ user_info.home ~ '/RetroPie' }}"
    depth: 1
    version: "{{ retropie_version }}"
  become: yes
  become_user: retropie
  tags:
    - retropie
    - update

- name: Install extra packages
  action: "{{ ansible_facts.pkg_mgr }}"
  args:
    name: "{{ retropie_extra_packages }}"
    state: latest
  tags:
    - retropie
    - packages

- name: Set locale
  locale:
  notify: restart system
  tags:
    - retropie
    - locale
    - config

- name: Set alternatives
  alternatives:
    name: editor
    path: /usr/bin/vim
  tags:
    - retropie
    - alternatives
    - config

- name: Copy getty@tty1 service file
  template:
    src: getty@tty1.service.j2
    dest: /lib/systemd/system/getty@.service
    owner: root
    group: root
    mode: '0644'
  notify: restart tty1
  tags:
    - retropie
    - config

- name: Disable screen blanking in console
  blockinfile:
    dest: /media/boot/boot.ini
    insertbefore: '^setenv bootargs'
    block: |
      setenv RetroPie "no_console_suspend consoleblank=0"

      # --- CPU Governor Setup ---
      # Uncomment only one line. New governor is set after 90secs after boot.
      # ------------------------------------------
      # - Performance (Keep all the CPU's at Maximum frequency)
      # setenv governor "performance"
      # ------------------------------------------
      # - Ondemand (recommended)
      setenv governor "ondemand"
  notify: restart system
  tags:
    - retropie
    - config

- name: Disable screen blanking in console
  lineinfile:
    state: present
    dest: /media/boot/boot.ini
    regexp: '^setenv bootargs'
    line: 'setenv bootargs "${bootrootfs} ${videoconfig} ${hdmi_phy_control} ${hud_quirks} smsc95xx.macaddr=${macaddr} ${external_watchdog} governor=${governor} ${RetroPie}"'
  notify: restart system
  tags:
    - retropie
    - config

- name: Stop and disable lightdm
  service:
    name: lightdm
    state: stopped
    enabled: no
  tags:
    - retropie
    - notest

- name: Set timezone
  timezone:
    name: "{{ retropie_timezone }}"
  tags:
    - retropie
    - timezone
    - notest

- debug:
    msg: |
      RetroPie successfully installed
      Follow platform specific instructions to complete setup: https://retropie.org.uk/docs/Debian/
  tags:
    - retropie
