- hosts: all
  become: true

  vars:
    retropie_extra_packages:
      - language-pack-en-base
      - libsdl2-dev
      - mplayer
      - pkg-config

  tasks:
    - debug:
        msg: >-
          Testing with Ansible {{ ansible_version.full }} using Python {{ ansible_facts.python_version }}
          on {{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}

    - name: TEST PREP | Install packages
      apt:
        name:
          - apt-utils
          - vim
        update_cache: yes
        state: present

    - name: TEST PREP | Create groups
      group:
        name: "{{ item }}"
      loop:
        - input
        - video

    - name: TEST PREP | Check for /media/boot
      stat:
        path: /media/boot
      register: boot

    - name: TEST PREP | Create /media/boot
      file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
      loop:
        - path: /media/boot
          state: directory

        - path: /media/boot/boot.ini
          state: touch
      when: not boot.stat.exists

    - import_role:
        name: retropie
